{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6af622c6-ec8e-4ae6-ae36-58fc88af4a69",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# -----------------------------\n",
    "# Helper functions\n",
    "# -----------------------------\n",
    "def cricket_overs_to_balls(overs):\n",
    "    overs_int = int(overs)\n",
    "    balls_part = int(round((overs - overs_int) * 10))\n",
    "    return overs_int * 6 + balls_part\n",
    "\n",
    "def balls_to_cricket_overs(balls):\n",
    "    overs = balls // 6\n",
    "    rem_balls = balls % 6\n",
    "    return float(f\"{int(overs)}.{int(rem_balls)}\")\n",
    "\n",
    "def corrected_actual_overs(row):\n",
    "    adjusted_ball = row['Actual Ball']\n",
    "    if row['Legal Ball'] != 'Yes':\n",
    "        adjusted_ball = max(0, adjusted_ball - 1)\n",
    "    if adjusted_ball == 6:\n",
    "        return float(f\"{int(row['Over'])}.0\")\n",
    "    else:\n",
    "        return float(f\"{int(row['Over']) - 1}.{int(adjusted_ball)}\")\n",
    "\n",
    "# -----------------------------\n",
    "# Load and preprocess data\n",
    "# -----------------------------\n",
    "data = pd.read_csv(\"C:/Users/rahul/anaconda_projects/1a85c8cd-a5a1-4bbd-ac45-903f158b07a8/9JuneuptoWT20.csv\")\n",
    "data.columns = data.columns.str.strip()\n",
    "data[['Team1', 'Team2']] = data['Match'].str.split(' v ', expand=True)\n",
    "data.sort_values(by=['Match', 'Date', 'Innings'], inplace=True)\n",
    "data['Next_Innings'] = data.groupby(['Match', 'Date'])['Innings'].shift(-1)\n",
    "mask = data['Innings'].ne(data['Next_Innings']) & (data.index < len(data))\n",
    "rows_before_change = data[mask].copy().reset_index(drop=True).drop(columns=['Next_Innings'])\n",
    "\n",
    "# -----------------------------\n",
    "# Compute Overs and NRR Balls\n",
    "# -----------------------------\n",
    "rows_before_change['Actual Overs'] = rows_before_change.apply(corrected_actual_overs, axis=1)\n",
    "rows_before_change['NRR Overs'] = rows_before_change.apply(\n",
    "    lambda row: 20.0 if row['Team Wickets'] == 10 else row['Actual Overs'], axis=1\n",
    ")\n",
    "rows_before_change['NRR Balls'] = rows_before_change['NRR Overs'].apply(cricket_overs_to_balls)\n",
    "\n",
    "# -----------------------------\n",
    "# Compute Team-wise summaries\n",
    "# -----------------------------\n",
    "for_summary = rows_before_change.groupby('Batting Team').agg({\n",
    "    'Team Runs': 'sum',\n",
    "    'NRR Balls': 'sum'\n",
    "}).reset_index().rename(columns={\n",
    "    'Batting Team': 'Team',\n",
    "    'Team Runs': 'Runs For',\n",
    "    'NRR Balls': 'NRR Balls For'\n",
    "})\n",
    "for_summary['Overs For'] = for_summary['NRR Balls For'].apply(balls_to_cricket_overs)\n",
    "for_summary.drop(columns='NRR Balls For', inplace=True)\n",
    "\n",
    "against_summary = rows_before_change.groupby('Bowling Team').agg({\n",
    "    'Team Runs': 'sum',\n",
    "    'NRR Balls': 'sum'\n",
    "}).reset_index().rename(columns={\n",
    "    'Bowling Team': 'Team',\n",
    "    'Team Runs': 'Runs Against',\n",
    "    'NRR Balls': 'NRR Balls Against'\n",
    "})\n",
    "against_summary['Overs Against'] = against_summary['NRR Balls Against'].apply(balls_to_cricket_overs)\n",
    "against_summary.drop(columns='NRR Balls Against', inplace=True)\n",
    "\n",
    "team_summary = pd.merge(for_summary, against_summary, on='Team', how='outer')\n",
    "\n",
    "# -----------------------------\n",
    "# Calculate NRR\n",
    "# -----------------------------\n",
    "team_summary['NRR Balls For'] = team_summary['Overs For'].apply(cricket_overs_to_balls)\n",
    "team_summary['NRR Balls Against'] = team_summary['Overs Against'].apply(cricket_overs_to_balls)\n",
    "team_summary['Run Rate For'] = team_summary['Runs For'] / (team_summary['NRR Balls For'] / 6)\n",
    "team_summary['Run Rate Against'] = team_summary['Runs Against'] / (team_summary['NRR Balls Against'] / 6)\n",
    "team_summary['NRR'] = (team_summary['Run Rate For'] - team_summary['Run Rate Against']).round(3)\n",
    "final_nrr_table = team_summary[['Team', 'Runs For', 'Overs For', 'Runs Against', 'Overs Against', 'NRR']]\n",
    "\n",
    "# -----------------------------\n",
    "# Compute Match Outcome Stats\n",
    "# -----------------------------\n",
    "match_results = []\n",
    "innings_grouped = rows_before_change.groupby(['Match', 'Date'])\n",
    "\n",
    "for (match, date), group in innings_grouped:\n",
    "    if len(group) == 2:\n",
    "        team1 = group.iloc[0]['Batting Team']\n",
    "        team2 = group.iloc[1]['Batting Team']\n",
    "        runs1 = group.iloc[0]['Team Runs']\n",
    "        runs2 = group.iloc[1]['Team Runs']\n",
    "\n",
    "        if runs1 > runs2:\n",
    "            match_results.extend([\n",
    "                {'Team': team1, 'W': 1, 'L': 0, 'T': 0, 'N/R': 0},\n",
    "                {'Team': team2, 'W': 0, 'L': 1, 'T': 0, 'N/R': 0},\n",
    "            ])\n",
    "        elif runs1 == runs2:\n",
    "            match_results.extend([\n",
    "                {'Team': team1, 'W': 0, 'L': 0, 'T': 1, 'N/R': 0},\n",
    "                {'Team': team2, 'W': 0, 'L': 0, 'T': 1, 'N/R': 0},\n",
    "            ])\n",
    "        else:\n",
    "            match_results.extend([\n",
    "                {'Team': team1, 'W': 0, 'L': 1, 'T': 0, 'N/R': 0},\n",
    "                {'Team': team2, 'W': 1, 'L': 0, 'T': 0, 'N/R': 0},\n",
    "            ])\n",
    "    else:\n",
    "        team1 = group.iloc[0]['Batting Team']\n",
    "        team2 = group.iloc[0]['Bowling Team']\n",
    "        match_results.extend([\n",
    "            {'Team': team1, 'W': 0, 'L': 0, 'T': 0, 'N/R': 1},\n",
    "            {'Team': team2, 'W': 0, 'L': 0, 'T': 0, 'N/R': 1},\n",
    "        ])\n",
    "\n",
    "results_df = pd.DataFrame(match_results)\n",
    "summary_stats = results_df.groupby('Team').sum().reset_index()\n",
    "summary_stats['M'] = summary_stats[['W', 'L', 'T', 'N/R']].sum(axis=1)\n",
    "summary_stats['PT'] = summary_stats['W'] * 4 + summary_stats['T'] * 2 + summary_stats['N/R'] * 2\n",
    "\n",
    "# -----------------------------\n",
    "# Merge with NRR Table\n",
    "# -----------------------------\n",
    "final_merged = pd.merge(summary_stats, final_nrr_table, on='Team', how='outer')\n",
    "\n",
    "# Bonus points input\n",
    "bonus_points = {\n",
    "    'Middlesex Women': 1,\n",
    "    'Yorkshire Women': 2,\n",
    "    'Derbyshire Falcons Women': 1\n",
    "}\n",
    "final_merged['BP'] = final_merged['Team'].map(bonus_points).fillna(0).astype(int)\n",
    "final_merged['PT'] += final_merged['BP']\n",
    "\n",
    "# Final formatted table\n",
    "final_display = final_merged[\n",
    "    ['Team', 'M', 'W', 'L', 'T', 'N/R', 'BP', 'PT', 'NRR',\n",
    "     'Runs For', 'Overs For', 'Runs Against', 'Overs Against']\n",
    "].sort_values(by=['PT', 'NRR'], ascending=[False, False]).reset_index(drop=True)\n",
    "\n",
    "final_display.index += 1\n",
    "\n",
    "# Define groupings\n",
    "north_group = ['Yorkshire Women', 'Northamptonshire Steelbacks Women', 'Derbyshire Falcons Women', 'Leicestershire Foxes Women', 'Worcestershire Rapids Women']\n",
    "south_group = final_display[~final_display['Team'].isin(north_group)]['Team'].tolist()\n",
    "\n",
    "# Split into two tables\n",
    "north_table = final_display[final_display['Team'].isin(north_group)].reset_index(drop=True)\n",
    "south_table = final_display[final_display['Team'].isin(south_group)].reset_index(drop=True)\n",
    "\n",
    "# Add rank index starting from 1\n",
    "north_table.index += 1\n",
    "south_table.index += 1\n",
    "\n",
    "def get_updated_tables(df, future_matches):\n",
    "    import pandas as pd\n",
    "\n",
    "    # Apply your existing logic here, adapted to use `df` and `future_matches`\n",
    "    # instead of reading CSV and building future_matches from Streamlit inputs\n",
    "\n",
    "    # Return: north_table, south_table as final two dataframes\n",
    "    return north_table, south_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d311db3d-1933-4413-be04-09eedfa4aac6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
